Repository dsccommunity/SharePointDsc, pull requests merged in 2018-09, with the labels that each got.

#865 Release 2.5
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/General.md
  .github/ISSUE_TEMPLATE/Problem_with_resource.md
  .github/ISSUE_TEMPLATE/Resource_proposal.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  Modules/SharePointDsc/DSCResources/MSFT_SPAppCatalog/MSFT_SPAppCatalog.psm1
  Modules/SharePointDsc/DSCResources/MSFT_SPAppCatalog/readme.md
  Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/Readme.md
  Modules/SharePointDsc/DSCResources/MSFT_SPDiagnosticsProvider/MSFT_SPDiagnosticsProvider.psm1
  Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1
  Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1
  Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.schema.mof
  Modules/SharePointDsc/DSCResources/MSFT_SPRemoteFarmTrust/MSFT_SPRemoteFarmTrust.psm1
  Modules/SharePointDsc/DSCResources/MSFT_SPRemoteFarmTrust/readme.md
  Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1
  Modules/SharePointDsc/DSCResources/MSFT_SPSearchTopology/MSFT_SPSearchTopology.psm1
  Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.schema.mof
  Modules/SharePointDsc/DSCResources/MSFT_SPShellAdmins/MSFT_SPShellAdmins.psm1
  Modules/SharePointDsc/DSCResources/MSFT_SPShellAdmins/MSFT_SPShellAdmins.schema.mof
  Modules/SharePointDsc/DSCResources/MSFT_SPSite/MSFT_SPSite.psm1
  Modules/SharePointDsc/DSCResources/MSFT_SPSiteUrl/MSFT_SPSiteUrl.psm1
  Modules/SharePointDsc/DSCResources/MSFT_SPSiteUrl/MSFT_SPSiteUrl.schema.mof
  Modules/SharePointDsc/DSCResources/MSFT_SPSiteUrl/readme.md
  Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuerProviderRealms/MSFT_SPTrustedIdentityTokenIssuerProviderRealms.psm1
  Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1
  Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.schema.mof
  Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/readme.md
  Modules/SharePointDsc/Examples/Resources/SPShellAdmins/3-ExcludeDatabases.ps1
  Modules/SharePointDsc/Examples/Resources/SPSite/2-SiteQuota.ps1
  Modules/SharePointDsc/Examples/Resources/SPSiteUrl/1-Example.ps1
  Modules/SharePointDsc/Examples/Resources/SPUserProfileServiceApp/3-SiteNamingConflictResolution.ps1
  Modules/SharePointDsc/SharePointDsc.psd1
  Modules/SharePointDsc/en-US/about_SPAppCatalog.help.txt
  Modules/SharePointDsc/en-US/about_SPDatabaseAAG.help.txt
  Modules/SharePointDsc/en-US/about_SPRemoteFarmTrust.help.txt
  Modules/SharePointDsc/en-US/about_SPServiceIdentity.help.txt
  Modules/SharePointDsc/en-US/about_SPShellAdmins.help.txt
  Modules/SharePointDsc/en-US/about_SPSite.help.txt
  Modules/SharePointDsc/en-US/about_SPSiteUrl.help.txt
  Modules/SharePointDsc/en-US/about_SPUserProfileServiceApp.help.txt
  Tests/Unit/SharePointDsc/SharePointDsc.SPAppCatalog.Tests.ps1
  Tests/Unit/SharePointDsc/SharePointDsc.SPDiagnosticsProvider.Tests.ps1
  Tests/Unit/SharePointDsc/SharePointDsc.SPFarm.Tests.ps1
  Tests/Unit/SharePointDsc/SharePointDsc.SPLogLevel.Tests.ps1
  Tests/Unit/SharePointDsc/SharePointDsc.SPSearchServiceApp.Tests.ps1
  Tests/Unit/SharePointDsc/SharePointDsc.SPSearchTopology.Tests.ps1
  Tests/Unit/SharePointDsc/SharePointDsc.SPShellAdmins.Tests.ps1
  Tests/Unit/SharePointDsc/SharePointDsc.SPSite.Tests.ps1
  Tests/Unit/SharePointDsc/SharePointDsc.SPSiteUrl.Tests.ps1
  Tests/Unit/SharePointDsc/SharePointDsc.SPTrustedIdentityTokenIssuerProviderRealms.Tests.ps1
  Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileServiceApp.Tests.ps1
  appveyor.yml
Labels: ready for merge

#886 SPWebAppPropertyBag: Added new resource for managing web application property bag.
  CHANGELOG.md
  Modules/SharePointDsc/DSCResources/MSFT_SPWebAppPropertyBag/MSFT_SPWebAppPropertyBag.psm1
  Modules/SharePointDsc/DSCResources/MSFT_SPWebAppPropertyBag/MSFT_SPWebAppPropertyBag.schema.mof
  Modules/SharePointDsc/DSCResources/MSFT_SPWebAppPropertyBag/readme.md
  Modules/SharePointDsc/Examples/Resources/SPWebAppPropertyBag/1-AddWebAppPropertyBag.ps1
  Modules/SharePointDsc/Examples/Resources/SPWebAppPropertyBag/2-RemoveWebAppPropertyBag.ps1
  Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPropertyBag.Tests.ps1
Labels: needs review

#889 Bugfix rollup
  CHANGELOG.md
  Modules/SharePointDsc/DSCResources/MSFT_SPSearchTopology/readme.md
  Modules/SharePointDsc/DSCResources/MSFT_SPSite/MSFT_SPSite.psm1
  Modules/SharePointDsc/DSCResources/MSFT_SPSite/MSFT_SPSite.schema.mof
  Modules/SharePointDsc/DSCResources/MSFT_SPSite/readme.md
  Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1
  Tests/Unit/SharePointDsc/SharePointDsc.SPExcelServiceApp.Tests.ps1
  Tests/Unit/SharePointDsc/SharePointDsc.SPSite.Tests.ps1
  Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileServiceApp.Tests.ps1
  Tests/Unit/UnitTestHelper.psm1
Labels: needs review

#890 AzureEnvironmentBuilder: VM max name length and fix for Azure PowerShell 6.0.0
  Tests/Integration/Azure/AzureEnvironmentBuilder.psm1
  Tests/Integration/Azure/template.json
Labels: waiting for code fix

#892 SPServiceAppSecurity: Added support for local farm token and fixed multiple issues
  CHANGELOG.md
  Modules/SharePointDsc/DSCResources/MSFT_SPServiceAppSecurity/MSFT_SPServiceAppSecurity.psm1
  Modules/SharePointDsc/DSCResources/MSFT_SPServiceAppSecurity/readme.md
  Modules/SharePointDsc/Examples/Resources/SPServiceAppSecurity/2-Example.ps1
  Tests/Unit/SharePointDsc/SharePointDsc.SPServiceAppSecurity.Tests.ps1
Labels: needs review

#876 Added New SPSearchManagedProperty Resource
  CHANGELOG.md
  Modules/SharePointDsc/DSCResources/MSFT_SPSearchManagedProperty/MSFT_SPSearchManagedProperty.psm1
  Modules/SharePointDsc/DSCResources/MSFT_SPSearchManagedProperty/MSFT_SPSearchManagedProperty.schema.mof
  Modules/SharePointDsc/DSCResources/MSFT_SPSearchManagedProperty/readme.md
  Modules/SharePointDsc/Examples/Resources/SPSearchManagedProperty/1-EnsureProperty.ps1
  Tests/Unit/SharePointDsc/SharePointDsc.SPSearchManagedProperty.Tests.ps1
Labels: needs review
